PUT http://localhost:3001/resources/3
Content-Type: application/json 

{
    "first_name" : "Recurso",
    "last_name" : "3",
    "role" : "admin",
    "availability" : "available",
    "created_by" : "admin",
    "modified_by" : "admin"
}