POST http://localhost:3001/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb3NlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzMzMzg5NjYsImV4cCI6MTc3MzM0MjU2Nn0.CF2WzcITjWWiere2WFyiS6grIg-xpoOiPvbdGUyLiGY

{
  "name" : "Projeto 9",
  "description" : "TESTE",
  "status" : "active",
  "created_by" : "admin",
  "modified_by" : "admin"
}