POST http://localhost:3001/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb3NlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM0MTc0NTUsImV4cCI6MTc3MzQyMTA1NX0.L3wApoAQvrX7cAQydFtYNlCSgksckkJRgY7exDrB-t8

{
  "name" : "Projeto ap",
  "description" : "TESTEES",
  "status" : "active",
  "created_by" : "admin",
  "modified_by" : "admin"
}