DELETE http://localhost:3001/projects/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb3NlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM0MDE1ODgsImV4cCI6MTc3MzQwNTE4OH0.zsyyKJbquiiHmqhPhGRgVKJM9fD-RSsHXRAqqvxdRHU
